name: build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetchDepth: 0
    - name: Install Go
      uses: actions/setup-go@v2.1.3
    - name: Import GPG key
      id: gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.SIGNING_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT : "${{ steps.gpg.outputs.fingerprint }}"
